---
- name: Create a VM from a template
  hosts: localhost
  vars_prompt:
    - name: vcenter_username
      prompt: What is vcenter username?
      private: false
    - name: vcenter_password
      prompt: What is your vcenter password?
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.1.1
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: RHEL7VMtest
      template: rhel-7-template
      datacenter: Konsalt-MESA
      folder: /Konsalt-MESA/RedHat/RHEL
      state: poweredon
      wait_for_ip_address: no
