---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.1.3
      username: "gultekin.keles"
      password: "Fb1907arda1*"
      validate_certs: False
      name: RHEL7VMtest
      template: rhel-7-template
      datacenter: Konsalt-MESA
      folder: /Konsalt-MESA/RedHat/RHEL
      state: poweredon
      wait_for_ip_address: no
