---
- name: Access OpenShift API
  hosts: localhost
  tasks:
    - name: Print Kubernetes Host and Token
      debug:
        msg:
          - "Kubernetes Host: {{ lookup('env', 'K8S_AUTH_API_URL') }}"
          - "Bearer Token: {{ lookup('env', 'K8S_AUTH_TOKEN') }}"
