---
- name: Access OpenShift API
  hosts: localhost
  tasks:
    - name: Print Kubernetes Host and Token
      debug:
        msg:
          - "Kubernetes Host: {{ lookup('env', 'host') }}"
          - "Bearer Token: {{ lookup('env', 'bearer-token') }}"
