---
- name: Login to OpenShift and execute Bash script
  hosts: localhost
  #gather_facts: false 
  tasks:
  - name: Log in (obtain access token)
    redhat.openshift.openshift_auth:
      host: https://api.ocpkobil.konsalt.info:6443
      username: kubeadmin
      password: "YkxGs-c23Mx-F99op-WtQB9"
      validate_certs: false
    register: openshift_auth_results
