---
- name: Use OpenShift or Kubernetes API Bearer Token
  hosts: localhost
  debug:
    var: ansible_env
  gather_facts: no
  vars:
    k8s_endpoint: "{{ lookup('env', 'host') }}"  # Credential'dan gelen API endpoint
    k8s_token: "{{ lookup('env', 'bearer-token') }}"        # Credential'dan gelen token
  tasks:
    - name: Debug API Endpoint and Token
      debug:
        msg:
          - "API Endpoint: {{ k8s_endpoint }}"
          - "Bearer Token: {{ k8s_token }}"
- name: Manage OpenShift Resources with Token
  hosts: localhost
  tasks:
    - name: List Pods
      kubernetes.core.k8s_info:
        api_key: sha256~ErGi8pZzgpNLmPl0hZqz_U2auwe4pcTK4idlzdrcL3E
        host: https://api.ocpkobil.konsalt.info:6443
        #host: "{{ ocp-kobil-kubeadmin.host }}"
        kind: Pod
        namespace: bgd
      register: pod_list

    - name: Run a Bash script
      ansible.builtin.shell: |
        #!/bin/bash
        echo "Running a Bash script on OpenShift cluster"
        oc --help
      args:
        executable: /bin/bash
      register: script_output
