---
- name: Login to OpenShift and execute Bash script
  hosts: localhost
  
  tasks:
  - name: Log in (obtain access token)
    redhat.openshift.openshift_auth:
      username: kubeadmin
      password: "YkxGs-c23Mx-F99op-WtQB9"
    register: openshift_auth_results
        # Previous task provides the token/api_key, while all other parameters
        # are taken from module_defaults
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      kind: Pod
    register: pod_list
    #always:
