---
- name: Login to OpenShift and execute Bash script
  hosts: localhost
  tasks:
    - name: Authenticate with OpenShift Cluster
      community.okd.openshift_auth:
        api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
        host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
        validate_certs: false
      register: k8s_auth_result

    - name: Fail if authentication failed
      ansible.builtin.fail:
        msg: "Failed to authenticate with OpenShift cluster"
      when: k8s_auth_result.failed

    - name: Run a Bash script
      ansible.builtin.shell: |
        #!/bin/bash
        echo "Running a Bash script on OpenShift cluster"
        echo "Cluster URL: {{ lookup('env', 'K8S_AUTH_HOST') }}"
        echo "Logged in using Bearer Token"
      args:
        executable: /bin/bash
      register: script_output

    - name: Display script output
      ansible.builtin.debug:
        msg: "{{ script_output.stdout }}"
