---
  - name: Yum list installed packages
    hosts: all
    tasks:
    - name: yum list installed packages and save to txt
      shell: |
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        echo $HOSTNAME >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        yum list installed | awk '{ print $1 }' >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        cp /tmp/yumlist.txt /tmp/"$HOSTNAME"-yumlist.txt
        cat /tmp/yumlist.txt
      register: deneme
    - debug: msg="{{deneme.stdout_lines}}"
    - name: ansible copy file from remote to local.
      fetch:
        src: /tmp/*.yumlist.txt
        dest: /tmp
        flat: yes
      register: fetch_output
    - debug: msg="{{fetch_output.stdout_lines}}"
    
#    - name: copy file from local to machine2
#        copy: 
#          src: /tmp/yumlist.txt
#          dest: /tmp/yumlist.txt
#    - name: Store file into /tmp
#      ansible.builtin.fetch:
#        hosts: localhost
#        src: /tmp/yumlist.txt
#        dest: /tmp
