---
  - name: Yum list installed packages
    hosts: all
    tasks:
    - name: yum list intalled packages and save to txt
      shell: |
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        echo $HOSTNAME >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        yum list installed | awk '{ print $1 }' >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        cp /tmp/yumlist.txt /tmp/"$HOSTNAME"-yumlist.txt
        cat /tmp/yumlist.txt
      register: deneme
    - debug: msg="{{deneme.stdout_lines}}"
    - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
      ansible.builtin.fetch:
        src: /tmp/yumlist.txt
        dest: /tmp
