---
- name: List installed packages on host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: List ansible packages and register result to print with debug later
    ansible.builtin.yum:
      list: "installed"
    register: result
