---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: List ansible packages and register result to print with debug later
  ansible.builtin.yum:
    list: ansible
  register: result
