---
  - name: Yum list installed packages
    hosts: all
    tasks:
    - name: yum list intalled packages and save to txt
      shell: |
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        echo $HOSTNAME >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        yum list installed | awk '{ print $1 }' >> /tmp/yumlist.txt
        echo "-----------------------------------------" >> /tmp/yumlist.txt
        cp /tmp/yumlist.txt /tmp/"$HOSTNAME"-yumlist.txt
        cat /tmp/yumlist.txt
      register: deneme
    - debug: msg="{{deneme.stdout_lines}}"
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /tmp/*-yumlist.tx
        dest: 192.168.70.11:/tmp
